stages:
  - test
  - docker_build
test:
 image: "python:3"
 stage: test
 script:
   - apt-get install make -qq
   - apt-get install python-pip -qq
   - make deps
   - make test
docker:
 image: docker:stable
 services:
   - docker:dind
 stage: docker_build
 script:
   - docker build -t myapp .
