language: python
services:
  -doker
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: calm-falls-57840
  api_key: ${HEROKU_API_KEY}
